services:
  - type: web
    name: asl-image-search-api
    runtime: docker
    plan: free
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: FRONTEND_ORIGIN
        value: https://sex-nsfw.github.io
